name: Fairness Audits CI

on: [push]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: pip install -r requirements.txt
    - name: Run bias audit
      run: python run_audit.py
